Feature/#8692r64ke add console features
yekashtalian/Book-Library pull request #6
Opened 2023-09-22 20:02 UTC by djiNNN13

2023-09-24 09:00 UTC, vr242kj reviewed
Желательно, чтобы название коммита соответствовало изменениям, которые в нем произошли. Не вижу здесь файла pom.xml.
Вот текст из задания.
The project should be based on maven:
- pom.xml in the root directory
- project's directory structure according to the maven's standard

2023-09-24 09:12 UTC, vr242kj requested changes
Я так понимаю, что в коммите 'Ignore unwanted files' ты пытаешься убрать папку 'target'. Но после занесения её в .gitignore, она всё равно осталась. Папку нужно дополнительно удалить.
Внимательно просмотри .gitignore и удали лишнее строчки. Разберись, как это работает. Кажется, будто ты его просто скопировал, но на самом деле там всё довольно просто. Уверен, ты сможешь.

2023-09-24 10:13 UTC, vr242kj requested changes

2023-09-24 10:13 UTC, vr242kj commented on Book-Library/src/main/java/Menu.java
> +          }
предлагаю вынести все случаи от 3 - 8 а также exit в отдельные методы.
Например `case "3" -> addNewReader();`
Также очень важный момент, так как у нас трехуровневая архитектура, коммуникацию с пользователем обрабатывает representation layer (выписывает данные и считывает данные), затем он просто передает их в service layer, где уже происходит обработка данных. В service layer не должно быть никаких print & scan.

2023-09-24 10:18 UTC, vr242kj commented on Book-Library/src/main/java/Menu.java
> +            System.out.println();
думаю в это коммите System.out.println(); - это дублирование кода, которое можно избежать.

2023-09-24 14:32 UTC, vr242kj requested changes

2023-09-24 14:32 UTC, vr242kj commented on .gitignore
> +.idea/*.xml
Необходимо хорошо понимать разницу между **/**name и name**/**, и удалить лишнее **/**.

2023-09-24 14:32 UTC, vr242kj commented on src/entities/Book.java
> +    this.id = count.getAndIncrement();
разве может быть id ноль?

2023-09-24 14:45 UTC, vr242kj commented on src/services/LibraryService.java
> +      System.err.println("No readers found for entity.Book ID = " + bookId);
У тебя в сервисе есть методы для взаимодействия с пользователем (print и scanner). Все это должно находиться в representation layer (папке 'ui', и в данном случае, в классе 'Menu'). В service layer только бизнес логика.

2023-09-24 14:53 UTC, vr242kj commented on src/views/Menu.java
>      while (!exitRequest) {
используй while (true)

2023-09-24 14:57 UTC, vr242kj commented on src/views/Menu.java
> +    showOptions = false;
нужно закрыть `input`, так как будешь использовать `while (true)`, то какой выход из цикла будет?

2023-09-24 15:52 UTC, vr242kj commented on src/views/Menu.java
> -            libraryService.registerNewReader(getUserInput());
думаю лучше libraryService.addNewReader()

2023-09-24 15:56 UTC, vr242kj commented on Book-Library/src/main/java/Library.java
> +  public void addReader(Reader reader) {
это метод по документации должен называться `saveReader()` и должен возвращать то что сохранил

2023-09-26 09:21 UTC, vr242kj commented on src/dao/BookDao.java
> +  void removeReader(Book book);
я бы назвал этот метод `returnBookToLibrary()`, и как параметр будет не `Book book`, a `int bookId`

2023-09-26 09:26 UTC, vr242kj commented on src/dao/BookDao.java
> +  Book save(Book book);
я бы для ясности переименовал с `Book book` на `Book bookToSave`

2023-09-26 09:29 UTC, vr242kj commented on src/dao/ReaderDao.java
> +  void removeReader(Reader reader);
удаление происходит по id, и правильное название метода `deleteById()`

2023-09-26 09:33 UTC, vr242kj commented on src/ui/Menu.java
> +  }
думаю этот метод не нужен

2023-09-26 09:43 UTC, vr242kj commented on src/ui/Menu.java
> +          case "8" -> showCurrentReaderOfBook();
я бы уточнил `showCurrentReaderOfBookById()`

2023-09-26 09:44 UTC, vr242kj commented on src/ui/Menu.java
> +          case "7" -> showBorrowedBooks();
я бы уточнил `showBorrowedBooksByReaderId()`

2023-09-26 09:49 UTC, vr242kj commented on src/ui/Menu.java
>    private static final String OPTIONS_MESSAGE =
Если значение (в нашем случае текст) не переиспользуется, то не нужно создавать переменную

2023-09-26 09:52 UTC, vr242kj commented on src/service/LibraryService.java
> +    bookDao.borrowBook(bookId, readerId);
а если `bookId `или `readerId ` не существует?

2023-09-26 11:44 UTC, yekashtalian commented on src/dao/ReaderDao.java
> +  void removeReader(Reader reader);
Я удалил этот метод, т.к. он нигде не использовался

2023-09-26 12:30 UTC, vr242kj commented on src/service/LibraryService.java
>    public Long showCurrentReaderOfBook(String userInput) throws InvalidIdException {
лучше String bookId

2023-09-26 12:32 UTC, vr242kj commented on src/service/LibraryService.java
>      int bookId = Integer.parseInt(userInput);
нет проверки существует ли книга

2023-09-26 12:34 UTC, vr242kj commented on src/service/LibraryService.java
>      }
Это просто сообщение, а не ошибка.

2023-09-26 17:55 UTC, vr242kj commented on src/service/LibraryService.java
> +  public Long showCurrentReaderOfBook(String bookIdToCheck) throws InvalidIdException {
возвращаемый тип должен быть `Optional<Reader>`

2023-09-26 17:58 UTC, vr242kj commented on src/service/LibraryService.java
>      int bookId = Integer.parseInt(bookIdToReturn);
int на long

2023-09-26 18:04 UTC, vr242kj commented on src/service/LibraryService.java
> +    Book book = bookDao.findById(bookId).orElseThrow(()-> new InvalidIdException(BOOK_NOT_FOUND));
где ты потом используешь `book`?

2023-09-26 18:07 UTC, vr242kj commented on src/service/LibraryService.java
> +    }
почему эта часть не в валидаторе?

2023-09-26 18:10 UTC, vr242kj commented on src/service/LibraryService.java
> +    String[] parts = book.split("/");
поменял бы `parts `на `nameAndAuthor`

2023-09-27 16:08 UTC, vr242kj commented on src/ui/Menu.java
> +  private void showAllBooks() {
не показывает, если в книги есть читатель.

2023-09-27 16:26 UTC, yekashtalian commented on src/ui/Menu.java
> +  private void showAllBooks() {
Не понял, если у книги есть читатель , то выводить возле книги его ID?

2023-09-27 16:42 UTC, vr242kj commented on src/ui/Menu.java
> +  private void showAllBooks() {
<img width="517" alt="image" src="https://github.com/yekashtalian/Book-Library/assets/88940299/414678df-a48a-44b0-bd1b-ac66d7e5c221">

2023-09-28 08:52 UTC, vr242kj approved these changes

2023-09-30 12:17 UTC, ahonsu commented on src/exception/InvalidBookTitleException.java
> +}
Комментарий по поводу всех кастомных типов исключений.
В наши дни стараюсь по возможности использовать unchecked exceptions.
Т.е. если ты создаешь свой тип, делай `extends RuntimeException`.
Почему? - значительно упрощает код, не нужно писать на всех методах `throws` и обработку исключений пишешь именно на том уровне, где тебе это требуется.

2023-09-30 12:17 UTC, ahonsu commented on src/service/Validator.java
> +  }
Соответствено здесь, если исключение будет unchecked - можно убрать из сигнатуры `throws`

2023-09-30 12:17 UTC, ahonsu commented on src/service/Validator.java
> +  }
Общий коммент по всем валидациям.
Давай представим, что наш пользователь мало понимает в валидацих и типичных требованиях к строкам (т.е. обычный человек). И он начинает печатать тебе новые имена.
Первая попытка - напечатал на кириллице. Ты ему показываешь "Name must contain at least one English letter!". Он такой, ОК понял.
Вторая попытка - напечатал на латинском, но добавил туда восклицательный знак. Ты ему - "Name must contain only English letters, spaces, dashes, and apostrophes!". Пользователь: ОК понял.
Третья попытка - печатает на латинице, убирает восклицательный знак, но имя из 4 символов. Ты ему - "Name must be longer than 5 characters!", он: ОК понял.
Четвертая попытка...

Чувствуешь где проблема?
Важно думать про свое приложение со стороны пользователя. Твой подход обработки ввода, скорее всего будет всех бесить и пользователь возможно вообще откажется от попыток создать новый объект.
Как исправить?
Сначала сделай ВСЕ валидации, которые есть в этом методе и в конце выбрасывай одно исключение, если хоть одна валидация не прошла. Плюс, печатай ему сообщение об ошибке, которое содержит сразу ВСЕ твои требования. Т.е. нужно сделать так, чтобы пользователь уже со второй попытки смог ввести корректное значение.

2023-09-30 12:17 UTC, singeev commented on src/service/LibraryService.java
> +    String authorName = bookAndAuthor[1];
Если это не ухудшает читаемость, используй
```
    var bookTitle = bookAndAuthor[0];
    var authorName = bookAndAuthor[1];
```
Пройдись по всему коду и замени там, где возможно. Это современный синтаксис, важно привыкать к этому.

2023-09-30 12:17 UTC, singeev commented on src/entity/Book.java
> +  }
Ты используешь этот конструктор 4 раза и всегда передаешь `readerId = 0`.
Либо убери этот параметр из конструктора вообще и сделай 0 по дефолту.
Либо добавть второй конструктор, без этого параметра.

2023-09-30 12:17 UTC, singeev commented on src/service/LibraryService.java
> +    String authorName = bookAndAuthor[1];
Второе, ты не делаешь `.trim()` для этих строк. Программа позволяет создать книгу, в которой у автора и названия будет куча пробелов до или после.

2023-09-30 12:17 UTC, singeev commented on src/dao/BookDaoImpl.java
> +  }
Не смотря на то, что выше по коду ты делаешь проверку, что такая книга существует - тут нельзя игнорировать ситуцаию, когда книги в листе нет.
Что если твой метод будет вызван из какого-то нового куска кода, другим разработчиком, который не знает про твои приколы?
Я бы рекомендовал тут использовать такую конструкцию:
```
public void returnBookToLibrary(long bookId) {
    findById(bookId)
        .ifPresentOrElse(
            book -> book.setReaderId(0),
            () -> new RuntimeException("error text here"));
  }
```
Только тип исключение и текст ошибки подставить правильные.

Пройдись по всем ДАО методам и устрани похожие проблемы.

2023-09-30 12:17 UTC, singeev commented on src/dao/BookDaoImpl.java
> +        .collect(Collectors.toList());
```suggestion
    return findAll().stream()
        .filter(book -> book.getReaderId() == readerId)
        .toList();
```
JDK 17

2023-09-30 12:17 UTC, singeev commented on src/ui/Menu.java
> +      }
Ты ловишь все 4 разных типа исключения и обрабатываешь их абсолютно одинаково.
Сразу вопрос: зачем тебе 4 разных типа?
Сделай один общий тип исключения, что-то вроде `LibraryProcessException` или `LibraryServiceException` и используй его везде вместо своих 4х типов.

В реальной жизни создают еще один новый тип исключения только если от этого есть какая-то польза. В первую очередь, если мы хотим исключение 1 обработать одним образом, а исключение 2 - другим.
У тебя нет никаких аргументов для создания сразу 4 разных типов.

2023-09-30 12:18 UTC, singeev commented on src/service/LibraryService.java
>      }
Я так понимаю, этот коммент тоже можно закрыть?
Код в этом месте уже выглядит норм.

2023-10-02 17:59 UTC, yekashtalian commented on src/service/LibraryService.java
> +    String authorName = bookAndAuthor[1];
`long bookId = Long.parseLong(ids[0].trim());`
стоит ли здесь использовать var?

2023-10-02 18:12 UTC, yekashtalian commented on src/dao/BookDaoImpl.java
> +  }
В таком случае можно ли в методе returnBookToLibrary из LibraryService убрать проверку:
`bookDao.findById(bookId).orElseThrow(() -> new LibraryServiceException(BOOK_NOT_FOUND));` ?
И вообще в методах сервиса, если я делаю проверку в ДАО?

2023-10-02 22:04 UTC, singeev commented on src/service/LibraryService.java
> +    String authorName = bookAndAuthor[1];
На мой взгляд, да. Само выражение явно показывает, что тип будет `long`.

2023-10-02 22:06 UTC, singeev commented on src/dao/BookDaoImpl.java
> +  }
В случае сценария возврата книги - точно можно убрать лишнюю проверку.
В других случаях нужно посмотреть на логику сценария. Если там тоже метод ДАО является узко-целевым, т.е. не может быть использован для другого сценария - тогда да, тоже можно убрать лишние проверки.

2023-10-04 12:51 UTC, singeev commented on src/dao/BookDaoImpl.java
> +  }
Вижу твой новый вариант кода. Ты добавил еще проверку, что книга на самом деле кому-то выдана, прежде чем ее возвращать.
Оно логично, но тут налицо нарушение нашей 3х слойной архитектуры и принципа single responsibility.
Т.е. получилось так, что метод ДАО "вернуть книгу" должен внутри себя принимать уже 2 решения: существует ли книга? и есть ли у нее читатель?
Второе решение не является необходимым для того, чтобы обнулить читателя. Т.е. даже если там уже стоит айди 0, ты можешь туда присвоить новое значение 0.
Это ответственность уровня сервиса этот вариант событий предусмотреть и сделать проверку.
При этом первую проверку сделать необходимо. Если такой книги нет вообще - ты не можешь туда присвоить айди читателя.

Поэтому я снова предлагаю вернуться к тому варианту, что я предложил выше.

2023-10-04 18:12 UTC, yekashtalian commented on src/dao/BookDaoImpl.java
> +  }
Хорошо, тогда можно устанавливать значени `readerId = 0` без выброса ошибки пользователю?
Ещё хотел уточнить по поводу borrowBook:
если книга уже кем-то взята, т.е. у неё `readerId != 0`, то я всё равно могу ее BORROW? В ТЗ, если не ошибаюсь не было условия, что книжка должна BORROW только из библотеки.

2023-10-04 19:22 UTC, singeev commented on src/dao/BookDaoImpl.java
> +  }
Если ход твоей программы уже дошел до этого ДАО метода и нигде не возникло других ошибок - да, в этом методе можно присвоить `readerId = 0`.
При этом на уровне сервиса (НЕ внутри ДАО) нужно сделать предварительные проверки:
1. Существует ли такая книга?
2. Выдана ли она в данный момент читателю?

Такие же соображения по поводу логики выдачи книги читателю. В сумме, все проверки должны быть сделаны, чтобы требования ТЗ были выполнены. Вопрос только в том, где именно их делать? - часть на уровне сервиса, часть на уровне ДАО.

Если все еще не понятно объяснил - переспроси!

2023-10-04 20:10 UTC, yekashtalian commented on src/dao/BookDaoImpl.java
> +  }
Ага, стало понятнее.
Потому что в предыдущем коммите я убрал предварительнуые проверки в методе сервиса.
Т.е. в методах ДАО returnBookToLibrary и borrowBook я делаю проверку существует ли книга, потому что кто-то может вызвать этот метод из другого участка кода и у него может вылететь exception.
Но тогда же нужно проверить и существует ли читатель с таким ID?
Потому что в метод borrowBook я передаю 2 параметра `borrowbook(long bookId, long readerId)`
Или я что то не так понял..

А что касается borrowBook, то я хотел узнать может ли читатель взять книгу, если она уже взята другим читателем?

2023-10-05 16:09 UTC, singeev commented on src/dao/BookDaoImpl.java
> +  }
Твой метод `bookDao.borrowBook(bookId, readerId)` физически не может знать, существует ли читатель с таким айди. При этом, твой способ хранения информации о связи читателя с книгой (поле readerId внутри объекта книги) - позволяет записать туда любого читателя, даже не существующего, никакой ошибки не будет, т.к. нет никаких ограничений.
Поэтому эти доп.проверки нужно делать на уровне сервиса. А именно: сервис должен проверить, что читатель с таким айди существует.

> А что касается borrowBook, то я хотел узнать может ли читатель взять книгу, если она уже взята другим читателем?

Не может.
Я рекомендую эту проверку (свободна книга для выдачи или нет) сделать тоже на уровне сервиса, прежде чем вызывать `bookDao.borrowBook(bookId, readerId)`.

> Но тут же вопрос, если кто-то захочет использовать этот метод в другом участке кода, то он в своем участке кода также должен проверить существует ли читатель с таким ID?

Да

2023-10-05 17:34 UTC, yekashtalian commented on src/dao/BookDaoImpl.java
> +  }
Я понял, спасибо.

2023-10-17 17:50 UTC, singeev approved these changes
Давай считать, что текущий тикет готов. Код можно мержить в мастер и начинать следующую задачу.

В коде есть некоторые недочеты, но они станут более заметны, когда мы начнем добавлять к проекту реальную БД. Пока все оставляем, как есть. Будем решать проблемы по мере их появления.

2023-10-17 18:08 UTC, merged