Feature/#8692r64k7-add-DB-to-the-project
yekashtalian/Book-Library pull request #7
Opened 2023-10-23 12:38 UTC by yekashtalian

2023-11-08 22:12 UTC, W25X80 requested changes

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +  private static final String SELECT_BY_ID_SQL = "SELECT * FROM book WHERE id = ?;";
Привет!
1. Лучшей практикой является по возможности не использовать `*`, а указывать конкретные столбцы.
Причина:
читаемость кода и поддержка кода. Если, к примеру, в бд добавить новые столбцы, то их извлечение может оказаться лишним, а другой разработчик об этом не будет знать.
производительность: насколько мне известно, в больших таблицах `*` проигрывает в эффективности.
Это касается всех SQL запросов, где есть `*`.

2. Точка с запятой используется для разделения отдельных команд или запросов и в подобных запросах она лишняя `?;"` Это не ошибка, просто как информация о лучших практиках)
Причина: согласно некоторым сообщениям на стековерфлоу некоторые фрейморки могут ошибаться при парсинге запроса.

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +  }
1. Метод очень красиво декомпозирован! Это справедливо для больших проектов, но в нашей задаче, по моему мнению, это избыточно. Александр подсказал классный принцип - нужно задавать вопрос "какие преимущества это дает в данном конкретном случае?".
❌ Читаемость и понятность --> в данном случае получилось наоборот.
❌ Повторное использование кода --> отсутствует.
✅ Упрощение тестирования. 
⛔ Упрощение отладки и рефакторинга. (Тут спорный вопрос)
⛔ Улучшение организации кода (да, но не во вред читаемости).

Фактически, этот метод и 4 его дочерних можно заменить буквально 13-15 строчками, которые легче понимать и поддерживать.

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +  }
В этом методе не вижу закрытия ресурса PreparedStatement. Если будет решение переделать код согласно предыдущему комментарию, то этот ресурс можно закрыть вместе с Connection.
Это же касается всех методов с PreparedStatement:

`private PreparedStatement prepareReturnStatement(long bookId, Connection connection);`

`private PreparedStatement prepareSelectByIdStatement(long bookId, Connection connection);`

`private PreparedStatement prepareBorrowStatement(long bookId, long readerId, Connection connection);`

 `private PreparedStatement prepareSelectByReaderIdStatement(long readerId, Connection connection);`
 
 Вот исчерпывающий ответ:
 
![image](https://github.com/yekashtalian/Book-Library/assets/78695319/d8e0b642-dac2-41ee-a208-acb4e9adba6c)

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +  }
На мой взгляд тут тоже красивая декомпозиция! На всякий случай напишу, что есть альтернативный вариант реализации с сокращением количества кода - заменить эти три метода на метод-маппер, который будет маппить resultSet в книгу. Мне этот код кажется тоже слегка избыточным, но это вероятно, на любителя. Нужно будет мнение Александра)

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/ReaderDaoImpl.java
> +  private static final String SELECT_BY_BOOK_ID_SQL = "SELECT reader.id, reader.name FROM reader INNER JOIN book ON reader.id = book.reader_id WHERE book.id = ?;";
Тут тоже вопрос со звездочками и точками-с-запятыми, как и в предыдущем классе.

2023-11-08 22:12 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +      throw new DaoOperationException("Cannot obtain book ID");
Нет обработки ситуаций, когда 
generatedId == 0 и если не удалось прочитать из колонки.

2023-11-09 10:07 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +  }
Привет!
У меня почти все методы так декомпозированы, тогда стоит по такому же принципу дочерные методы вместить в 1 метод?

2023-11-09 12:31 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +  }
Да, в этом примере я бы тоже все сделал в одном методе.
Обычно критерием для выделения куска кода в новый метод является отдельное завершенное действие. В данном случае, самый верхний метод и так делает одно действие "конвертирует resultSet в коллекцию книг".
Выделить в отдельный метод парсинг каждой строки, в целом, норм идея. Т.е. разбить один метод на два.
И тогда вместо `parseRow` и `createFromResultSet` был бы один метод - тот же `parseRow` например, но включающий код из обоих методов.

В общем, меня бы устроил один из вариантов:
1. Весь этот код в одном методе
2. Разбивка на 2 метода

Разбивка на 3 метода тут выглядит лишней.

2023-11-09 12:48 UTC, W25X80 commented on src/main/java/dao/BookDaoImpl.java
> +  }
Лично я бы предпочел переделать, но думаю это не критично, т.к. код в целом продуманно написан и ошибок мало. Просто с точки зрения логики мне кажется оправданным потренироваться не только хорошо декомпозировать, но и постараться применить кун-фу для  сокращения и  упрощения кода, сильно не нарушая при этом принципы SOLID и тд)
Как одно из преимуществ - в одном методе легче контролировать открытие-закрытие ресурсов. Если все методы таким образом переделать, то код станет короче и понятней ровно в 2 раза, а может и еще короче, главное не перегнуть палку.

2023-11-16 14:23 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +  private static final String SELECT_BY_ID_SQL = "SELECT * FROM book WHERE id = ?;";
Исправил.

2024-01-04 15:49 UTC, singeev requested changes

2024-01-04 15:49 UTC, ahonsu commented on src/main/java/dao/BookDaoImpl.java
> +      "SELECT id, name, author, reader_id FROM book WHERE reader_id = ?";
Если перенести каждый из этих SQL-запросов внутрь соответствующего метода - будет проще читать.
На уровень класса запросы выносят если в этом есть необходимость. Например, один и тот же запрос используется в нескольких методах. Или запрос динамический и собирается из нескольких частей в разных методах.

У тебя ничего такого нет, поэтому нет смысла держать их в качестве полей класса, и тем более статик файнал.

2024-01-04 15:49 UTC, ahonsu commented on src/main/java/dao/BookDaoImpl.java
> +    Objects.requireNonNull(bookToSave);
Согласен, что такую проверку сделать нужно.

Но у тебя нет обработки исключения. Если книга == null, это исключение полетит на самый верх и пользоватею будет напечатано сообщение, которое ты не котролируешь.

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +          }
Если ты не смог получить сгенерированный айди - это означет, что ты не смог сохранить/создать новую книгу. Поэтому:
1. Твое сообщение об ошибке "Book ID cannot be 0" - не верное
2. Исключение которое возникает на строке 31 можно ловить на строке 42, вместе со всеми остальными и писать то же сообщение об ошибке - которое у тебя на строке 43.

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +      }
В идеале сделать отдельную явную проверку на уровне сервиса - есть ли такая книга в БД или нет? Прежде чем пытаться ее вернуть.

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +          var book = parseRow(resultSet);
`parseRow` не самое удачное название. Типично такой метод называют `mapToBook` или `mapResultSetToBook`

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +        return collectToList(resultSet);
название метода плохое. Лучше `mapResultSetToBooksList`

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +      try(var resultSet = statement.executeQuery(SELECT_ALL_SQL)){
нет необходимости оборачивать это в `try-with-resources` здесь - ни ради обработки исключения, ни ради закрытия ресурса

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +      }
Аналогично. Сделай отдельную проверку на уровне сервиса для этого и используй везде, где она требуется.

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/DBUtil.java
> +            connection = DriverManager.getConnection(url, userName, password);
Лишняя переменная, можно сразу делать `return`

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/DBUtil.java
> +        }
Тут интересная ситуация. Программа стартует, пользователь начинает работать. Видит сообщение, что нет коннекта к БД. Программа продолжает предлагать ему меню и он продолжает пробовать... ничего не работает и он видит эту же ошибку снова и снова. И ничего не может с ней сделать.

В такой ситуации обычно есть 2 варианта:
1. Пользователю говорят что-то вроде "У нас большая проблема, ничего не работает, приходите позже" или "... обратитесь в тех.поддержку"
2. То же самое сообщение из п. 1 + принудительно завершают программу. Чтобы пользователь не залипал там перед экраном.

Предлагаю сделать принудительное завершение программы.

2024-01-04 15:49 UTC, singeev commented on src/main/java/dao/ReaderDaoImpl.java
> +public class ReaderDaoImpl implements ReaderDao {
По сути все комменты для ДАО книг справедливы и здесь, не буду их повторять. Пройдись по этим же вопросам и для этого класса!

2024-02-12 16:52 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +    Objects.requireNonNull(bookToSave);
То есть мне нужно завернуть это в блок try и в catch ловить этот NullPointerException?
И насколько вообще хорошая практика ловить NullPointerException? А не блоком if проверять?

2024-02-15 20:00 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +      "SELECT id, name, author, reader_id FROM book WHERE reader_id = ?";
Исправил.

2024-02-15 20:00 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +    Objects.requireNonNull(bookToSave);
Исправил.

2024-02-15 20:00 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +          }
Исправил.

2024-02-15 20:00 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +      }
Исправил.

2024-02-15 20:01 UTC, yekashtalian commented on src/main/java/dao/DBUtil.java
> +        }
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +          var book = parseRow(resultSet);
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +      try(var resultSet = statement.executeQuery(SELECT_ALL_SQL)){
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/BookDaoImpl.java
> +      }
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/DBUtil.java
> +            connection = DriverManager.getConnection(url, userName, password);
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/ReaderDaoImpl.java
> +public class ReaderDaoImpl implements ReaderDao {
Исправил.

2024-02-15 20:02 UTC, yekashtalian commented on src/main/java/dao/DBUtil.java
> +        }
Исправил.

2024-03-25 11:23 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +      "SELECT id, name, author, reader_id FROM book WHERE reader_id = ?";
Твой вариант: 
```
String INSERT_SQL = "INSERT INTO book(name, author) VALUES(?, ?)";
```

Какие проблемы с этим?
* постарайся во всех подобных случаях использовать `var` вместо объявления типа. Когда тип переменной и так очевиден
* название переменной заглавными буквами - это стандарт для констант, т.е. статических переменных уровня класса. Это не твой случай, поэтому нужен обычный camel case

2024-03-25 11:28 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +    Objects.requireNonNull(bookToSave);
Твой вариант:
```
    } catch (NullPointerException e) {
      throw new DaoOperationException(e.getMessage());
    }
```

Есть смысл заменить `e.getMessage()` на какое-то свое вразумительное сообщение.

2024-03-25 11:32 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +        return collectToList(resultSet);
Не вижу изменений.
Комментарий относился к этому методу:

`private List<Book> collectToList(ResultSet resultSet) throws SQLException`

2024-03-25 11:35 UTC, singeev commented on src/main/java/dao/DBUtil.java
> +        }
Твой код:
```
        } catch (SQLException e) {
            System.exit(0);
            throw new RuntimeException("Unable to establish database connection", e);
        }
```
В твоей реализации программа завершится раньше, чем будет выброшено (и напечатано юзеру) исключение.

2024-03-27 15:18 UTC, singeev commented on src/main/java/dao/DBUtil.java
> +        }
Новый вариант лучше, но тоже не супер.
Я предлагаю тебе создать новый тип исключения, выбрасывать его вместо `RuntimeException`, ловить его где-то на уровне меню и там писать пользователю сообщения и завершать программу.

2024-03-27 15:19 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +        return collectToList(resultSet);
Все еще нет изменений.

2024-03-27 15:27 UTC, yekashtalian commented on src/main/java/dao/DBUtil.java
> +        }
А стоит создавать новое исключения для 1 такого случая? Или это впринципе хорошая практика?

2024-03-28 10:21 UTC, singeev commented on src/main/java/dao/BookDaoImpl.java
> +        return collectToList(resultSet);
Для ДАО книг изменения вижу, для ДАО читателей - нет.

2024-03-28 10:31 UTC, singeev commented on src/main/java/dao/DBUtil.java
> +        }
Теперь много всего смешалось в одну кучу )
Давай еще раз проговорим, что нам требуется.
1. Мы пишем сообщения пользователю только на уровне "репрезентации", т.е. ты не печатаешь в консоль сообщения ни в сервисах, ни в ДАО... только в классе `Menu`
2. Если у тебя где-то возникает ошибка и нужно об этом сообщить пользователю - ты выбрасываешь исключение, внутри которого лежит нужное сообщение, ловишь это исключение на уровне `Menu`, достаешь из него сообщение, печатаешь его в консоль
3. При этом не на каждую ошибку нужно принудительно завершать работу приложения. Какие ошибки являются поводом остановить приложение? - только те, которые говорят об очень серьезных проблемах. В твоем случае это 2 ситуации: (1) не смогли прочитать проперти из файла и (2) не смогли создать подключение к БД. Т.е. обе ситуации у тебя происходят внутри класса `DBUtil`


Что я предлагаю?
- создать новый тип исключения, специально под эти 2 ситуации. Назвать его соответствующим образом, например, `DBConfigurationError`
- в классе `DBUtil` выбрасывать именно это исключение
- ловить его на уровне `Menu`, печатать пользователю сообщение и закрывать программу
- во всех других случаях (исключениях) программу закрывать не нужно
- убедиться, что у тебя нигде не происходит печати текста в консоль за пределами класса `Menu`

2024-03-29 14:08 UTC, singeev commented
Все замечания исправлены. Можно мержить.

2024-03-29 14:08 UTC, singeev approved these changes

2024-03-29 14:11 UTC, merged